name: Backend CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8

      - name: Install dependencies | Lint
        run: |
          cd starter/backend
          pipenv install
          pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8

      - name: Install dependencies | Test
        run: |
          cd starter/backend
          pipenv install
          pipenv run lint

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Build Docker image
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .
          